### ISSUE TITLE
Set configurations for reporters directly inside `reporterOptions`

### ISSUE THREAD

**Issue by AlehVasilyeu** [stanleyhlng/mocha-multi-reporters#31]
It would be great to set configurations for reporters directly inside `reporterOptions`.

### Expected behavior
Pass all configuration in `reporterOptions` instead specifying `reporterOptions.configFile`

### Actual behavior
Need to create config.json

**Comment by stanleyhlng** [comment]
Hi @AlehVasilyeu, 

Thank you for your suggestions, that's a good idea to pass options directly instead of specifying an external `config.json` file

Do you have any proposal?

### CURRENT IMPLEMENTATION w/ CONFIG.JSON
$ ./node_modules/.bin/mocha --reporter mocha-multi-reporters --reporter-options configFile=config.json

```
// File: config.json
{
    "reporterEnabled": "tap, xunit",
    "xunitReporterOptions": {
        "output": "xunit-custom.xml"
    }
}
```

**Comment by AlehVasilyeu** [comment]
@stanleyhlng Hi

Mocha can get reporter options programatically

```javascript
var mocha = new Mocha({
  reporter: 'reporter',
  reporterOptions: {
    ...
  }
});
```

What if reporterOptions will be configured like this:

```javascript
reporterOptions: [
  {
     reporter: "reporter1",
     reporterOptions: { }
  },
  {
     reporter: "reporter2",
     reporterOptions: { }
  }
]
```

And maybe somehow combine with previous implementation, so it will be possible to use CLI also.

What do you think? :)

**Comment by panmona** [comment]
Is there any way to supply the additional options via the CLI as well?
