### ISSUE TITLE
Repository Maintenance?

### ISSUE THREAD

**Issue by YOU54F** [stanleyhlng/mocha-multi-reporters#63]
Thank you for the repository @stanleyhlng

I have noticed that the repository does not appear to be actively maintained.

I have  a maintained fork that works with Mocha 6 and below at the following location

https://github.com/YOU54F/cypress-multi-reporters

and have provided a fix in the form of PR against this repository.

I thought I would raise this issue, for those viewing this repository and requiring a maintained fork. 👍

**Comment by francisu** [comment]
Hi @YOU54F, I'm now maintaining this repo and have dealt with the outstanding PRs. I welcome other PRs to handle the Mocha version issues.

**Comment by francisu** [comment]
Released 1.5.1 which has taken all of the cypress-multi-reporter changes.

**Comment by YOU54F** [comment]
Hey @francisu would you like to look at allowing consumers of cmr to actually consume mmr instead and deprecate the fork, or allow the fork to map through to this project? I'm not sure if that is possibly, but it makes sense to not have two distinct maintained forks of the same code, and I can spend the time on other things 👍🏾

**Comment by francisu** [comment]
@YOU54F Yes, thanks for your suggestion. I think to do this, I would need to be a collaborator on the npm cypress-multi-reporters package. And then when I publish a new version, I can publish to both npm modules (I can figure that out). The source code from the cypress package can be pointed to the package here.

I also made a change to accept both "mmrOptions" and "cmrOptions" in the report options so that everyone's code will work.
